import Product from "./products";

export const headsets = [
    new Product(11,
      "Headset Gamer ProX",
      "Headset gamer com som surround e microfone retrátil.",
      249.99,
      "./e-commerce/images/mouses/anthony-choren-e7dG26YCrZU-unsplash.jpg",
      "headset",
      "XGaming",
      "Som surround 7.1, microfone retrátil com cancelamento de ruído, design confortável.",
      85
    ),
    new Product(12,
      "Headset Bluetooth SoundWave",
      "Headset sem fio com conectividade Bluetooth e som de alta qualidade.",
      199.99,
      "./e-commerce/images/mouses/anthony-choren-e7dG26YCrZU-unsplash.jpg",
      "headset",
      "SoundTech",
      "Conexão Bluetooth 5.0, drivers de 40mm para som imersivo, bateria de longa duração.",
      70
    ),
    new Product(13,
      "Headset Gamer TurboFire",
      "Headset gamer com iluminação RGB e controle de volume integrado.",
      149.99,
      "./e-commerce/images/mouses/anthony-choren-e7dG26YCrZU-unsplash.jpg",
      "headset",
      "TurboGaming",
      "Iluminação RGB personalizável, drivers de 50mm, controle de volume no cabo.",
      90
    ),
    new Product(14,
      "Headset Estéreo ProSound",
      "Headset estéreo com fio e isolamento de ruído externo.",
      79.99,
      "./e-commerce/images/mouses/anthony-choren-e7dG26YCrZU-unsplash.jpg",
      "headset",
      "ProAudio",
      "Almofadas acolchoadas, cabo de 2 metros, compatível com PC e consoles.",
      65
    ),
    new Product(15,
      "Headset USB Premium",
      "Headset com conexão USB e qualidade de som cristalina.",
      129.99,
      "./e-commerce/images/mouses/anthony-choren-e7dG26YCrZU-unsplash.jpg",
      "headset",
      "PremiumSound",
      "Conexão USB, drivers de 50mm, controle de volume no fio.",
      80
    ),
  ];
  