import Product from "./products";

export const mouses = [
    new Product(1,
    "Mouse Gamer Xtreme",
    "Mouse gamer avançado com design ergonômico e botões programáveis",
    249.99,
    "/images/mouses/anthony-choren-e7dG26YCrZU-unsplash.jpg",
    "mouse",
    "HytorX",
    "Sensor óptico de 16000 DPI, iluminação RGB personalizável, conexão com fio.",
    34),
    new Product(2,
    "Mouse Sem Fio ProLite",
    "Mouse sem fio ergonômico com precisão e conforto para uso diário.",
    149.99,
    "/images/mouses/anthony-choren-e7dG26YCrZU-unsplash.jpg",
    "mouse",
    "Logibeck",
    "Sensor óptico de 1000 DPI, conexão sem fio de 2.4 GHz, autonomia de bateria de até 12 meses.",
    64),
    new Product(3,
    "Mouse Gamer StealthFire",
    "Mouse gamer de alta performance com design agressivo e botões programáveis.",
    349.99,
    "/images/mouses/anthony-choren-e7dG26YCrZU-unsplash.jpg",
    "mouse",
    "Rasor",
    " Sensor a laser de 20000 DPI, iluminação Chroma RGB personalizável, cabo trançado de alta durabilidade.",
    77),
    new Product(4,
    "Mouse ErgoTech Comfort",
    "Mouse ergonômico com design confortável e ajustável para reduzir o estresse muscular.",
    99.99,
    "/images/mouses/anthony-choren-e7dG26YCrZU-unsplash.jpg",
    "mouse",
    "Microhard",
    "Sensor óptico de 1200 DPI, botões laterais programáveis, compatível com ambas as mãos.",
    87),
    new Product(5,
    "Mouse Sem Fio Compacto",
    "Mouse sem fio compacto e portátil, ideal para uso em notebooks e viagens.",
    79.99,
    "/images/mouses/anthony-choren-e7dG26YCrZU-unsplash.jpg",
    "mouse",
    "HT",
    "Sensor óptico de 800 DPI, conexão sem fio de 2.4 GHz, receptor USB nano, economia de energia automática.",
    56),
]